modules-search: [ local ]

instances:
  - id: kaizen-bls-fix
    module: shellprocess
    config: shellprocess-kaizen-bls-fix.conf
  - id: kaizen-installed-cleanup
    module: shellprocess
    config: shellprocess-kaizen-installed-cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
# KAIZEN-FEDORA disabled Debian-only module:       - initramfs
      - grubcfg
      - bootloader
      - shellprocess@kaizen-bls-fix
      - shellprocess@kaizen-installed-cleanup
      - umount
  - show:
      - finished

branding: kaizen

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false
hide-back-and-next-during-exec: false
