---
dontChroot: false
timeout: 30
script:
  - command: "if [ -d /boot/loader/entries ]; then sed -i -e 's|linux /boot/vmlinuz-|linux /@boot/vmlinuz-|g' -e 's|initrd /boot/initramfs-|initrd /@boot/initramfs-|g' /boot/loader/entries/*.conf; fi"
