#!/usr/bin/env bash
set -euo pipefail

WALL="${1:-$HOME/.config/hypr/current_wallpaper}"
CACHE_DIR="$HOME/.cache/kaizen/theme"
ROFI_DIR="$HOME/.config/rofi"
WAYBAR_DIR="$HOME/.config/waybar"
KITTY_DIR="$HOME/.config/kitty"
HYPR_DIR="$HOME/.config/hypr"

mkdir -p "$CACHE_DIR" "$ROFI_DIR" "$WAYBAR_DIR" "$KITTY_DIR" "$HYPR_DIR"

# Stable Kaizen fallback palette.
# Later this can be replaced by matugen/Quickshell-generated colours.
BACKGROUND="#0b0b12"
SURFACE="#141420"
SURFACE_ALT="#1d1d2d"
FOREGROUND="#f4f2ff"
MUTED="#a9a4c7"
ACCENT="#9d7cff"
ACCENT_2="#67d8ff"
DANGER="#ff6b8a"
SUCCESS="#7dffb2"
BORDER="#2d2940"

cat > "$CACHE_DIR/colors.env" <<THEME
BACKGROUND="$BACKGROUND"
SURFACE="$SURFACE"
SURFACE_ALT="$SURFACE_ALT"
FOREGROUND="$FOREGROUND"
MUTED="$MUTED"
ACCENT="$ACCENT"
ACCENT_2="$ACCENT_2"
DANGER="$DANGER"
SUCCESS="$SUCCESS"
BORDER="$BORDER"
WALLPAPER="$WALL"
THEME

cat > "$CACHE_DIR/colors.json" <<THEME
{
  "background": "$BACKGROUND",
  "surface": "$SURFACE",
  "surfaceAlt": "$SURFACE_ALT",
  "foreground": "$FOREGROUND",
  "muted": "$MUTED",
  "accent": "$ACCENT",
  "accent2": "$ACCENT_2",
  "danger": "$DANGER",
  "success": "$SUCCESS",
  "border": "$BORDER",
  "wallpaper": "$WALL"
}
THEME

cat > "$ROFI_DIR/kaizen-adaptive.rasi" <<THEME
* {
  bg: $BACKGROUND;
  bg-alt: $SURFACE;
  surface: $SURFACE_ALT;
  fg: $FOREGROUND;
  muted: $MUTED;
  accent: $ACCENT;
  accent2: $ACCENT_2;
  border: $BORDER;

  background-color: transparent;
  text-color: @fg;
  font: "JetBrainsMono Nerd Font 11";
}

window {
  background-color: @bg;
  border: 2px;
  border-color: @accent;
  border-radius: 18px;
  padding: 18px;
  width: 520px;
}

mainbox {
  background-color: transparent;
  spacing: 10px;
}

inputbar {
  background-color: @bg-alt;
  border-radius: 14px;
  padding: 12px;
  spacing: 10px;
}

prompt {
  text-color: @accent;
}

entry {
  placeholder: "Search Kaizen";
  text-color: @fg;
}

listview {
  background-color: transparent;
  border-radius: 14px;
  spacing: 6px;
  lines: 10;
  fixed-height: false;
}

element {
  background-color: transparent;
  border-radius: 12px;
  padding: 10px;
}

element selected {
  background-color: @surface;
  text-color: @fg;
}

element-text {
  background-color: transparent;
  text-color: inherit;
}
THEME

cat > "$WAYBAR_DIR/kaizen-adaptive.css" <<THEME
@define-color kaizen_bg $BACKGROUND;
@define-color kaizen_surface $SURFACE;
@define-color kaizen_surface_alt $SURFACE_ALT;
@define-color kaizen_fg $FOREGROUND;
@define-color kaizen_muted $MUTED;
@define-color kaizen_accent $ACCENT;
@define-color kaizen_accent2 $ACCENT_2;
@define-color kaizen_border $BORDER;
@define-color kaizen_danger $DANGER;
@define-color kaizen_success $SUCCESS;
THEME

cat > "$KITTY_DIR/kaizen-adaptive.conf" <<THEME
background $BACKGROUND
foreground $FOREGROUND
selection_background $SURFACE_ALT
selection_foreground $FOREGROUND
cursor $ACCENT

color0 $BACKGROUND
color1 $DANGER
color2 $SUCCESS
color3 $ACCENT_2
color4 $ACCENT
color5 $ACCENT
color6 $ACCENT_2
color7 $FOREGROUND
color8 $MUTED
color9 $DANGER
color10 $SUCCESS
color11 $ACCENT_2
color12 $ACCENT
color13 $ACCENT
color14 $ACCENT_2
color15 $FOREGROUND
THEME

cat > "$HYPR_DIR/colors.conf" <<THEME
# Auto-generated by kaizen-generate-theme.sh
\$kaizen_bg = rgb(${BACKGROUND#"#"})
\$kaizen_surface = rgb(${SURFACE#"#"})
\$kaizen_fg = rgb(${FOREGROUND#"#"})
\$kaizen_muted = rgb(${MUTED#"#"})
\$kaizen_accent = rgb(${ACCENT#"#"})
\$kaizen_accent2 = rgb(${ACCENT_2#"#"})

# Compatibility aliases for older rice config
\$primary = rgb(${ACCENT#"#"})
\$surface_container = rgb(${SURFACE#"#"})
THEME

# Make Waybar load adaptive colours if possible.
if [ -f "$WAYBAR_DIR/style.css" ] && ! grep -q "kaizen-adaptive.css" "$WAYBAR_DIR/style.css"; then
  tmp="$(mktemp)"
  printf '@import "kaizen-adaptive.css";\n' > "$tmp"
  cat "$WAYBAR_DIR/style.css" >> "$tmp"
  mv "$tmp" "$WAYBAR_DIR/style.css"
fi

# Make Kitty load adaptive colours if possible.
if [ -f "$KITTY_DIR/kitty.conf" ] && ! grep -q "kaizen-adaptive.conf" "$KITTY_DIR/kitty.conf"; then
  printf '\n# Kaizen adaptive colours\ninclude kaizen-adaptive.conf\n' >> "$KITTY_DIR/kitty.conf"
fi

notify-send "Kaizen Theme" "Adaptive colours regenerated" 2>/dev/null || true
